language: android
# Workaround to get travis to user Android 27: https://github.com/travis-ci/travis-ci/issues/8874
before_install:
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-28"

env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - ANDROID_API=28
  - EMULATOR_API=22
  - ANDROID_BUILD_TOOLS=28.0.3
  - QEMU_AUDIO_DRV=none

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API
  - extra-google-google_play_services
  - sys-img-armeabi-v7a-google_apis-$EMULATOR_API

before_script:
- cd project
- android list targets
- echo no | android create avd --force -n test -t android-$EMULATOR_API --abi google_apis/armeabi-v7a
- emulator -avd test -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

